# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-05 20:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('terraform', '0007_historicalstate_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnamespace',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalnamespace',
            name='locking_user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='namespace',
            name='locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='namespace',
            name='locking_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
