# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-09-17 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('terraform', '0008_auto_20170905_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnamespace',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='locked'),
        ),
        migrations.AlterField(
            model_name='historicalnamespace',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='locked',
            field=models.BooleanField(default=False, verbose_name='locked'),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='locking_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locked_namespaces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='namespace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to='auth.Group'),
        ),
    ]
